
BR_BANK_CHOICES = (
    ('001', 'BCO DO BRASIL S.A.'),
    ('003', 'BCO DA AMAZONIA S.A.'),
    ('004', 'BCO DO NORDESTE DO BRASIL S.A.'),
    ('007', 'BNDES'),
    ('010', 'CREDICOAMO'),
    ('011', 'C.SUISSE HEDGING-GRIFFO CV S/A'),
    ('012', 'BANCO INBURSA'),
    ('014', 'STATE STREET BR S.A. BCO COMERCIAL'),
    ('015', 'UBS BB CCTVM S.A.'),
    ('016', 'CCM DESP TRÂNS SC E RS'),
    ('017', 'BNY MELLON BCO S.A.'),
    ('018', 'BCO TRICURY S.A.'),
    ('021', 'BCO BANESTES S.A.'),
    ('024', 'BCO BANDEPE S.A.'),
    ('025', 'BCO ALFA S.A.'),
    ('029', 'BANCO ITAÚ CONSIGNADO S.A.'),
    ('033', 'BCO SANTANDER (BRASIL) S.A.'),
    ('036', 'BCO BBI S.A.'),
    ('037', 'BCO DO EST. DO PA S.A.'),
    ('040', 'BCO CARGILL S.A.'),
    ('041', 'BCO DO ESTADO DO RS S.A.'),
    ('047', 'BCO DO EST. DE SE S.A.'),
    ('060', 'CONFIDENCE CC S.A.'),
    ('062', 'HIPERCARD BM S.A.'),
    ('063', 'BANCO BRADESCARD'),
    ('064', 'GOLDMAN SACHS DO BRASIL BM S.A'),
    ('065', 'BCO ANDBANK S.A.'),
    ('066', 'BCO MORGAN STANLEY S.A.'),
    ('069', 'BCO CREFISA S.A.'),
    ('070', 'BRB - BCO DE BRASILIA S.A.'),
    ('074', 'BCO. J.SAFRA S.A.'),
    ('075', 'BANCO ABN AMRO CLEARING S.A.'),
    ('076', 'BCO KDB BRASIL S.A.'),
    ('077', 'BANCO INTER'),
    ('078', 'HAITONG BI DO BRASIL S.A.'),
    ('079', 'PICPAY BANK - BANCO MÚLTIPLO S.A'),
    ('080', 'BT CC LTDA.'),
    ('081', 'BANCOSEGURO S.A.'),
    ('082', 'BANCO TOPÁZIO S.A.'),
    ('083', 'BCO DA CHINA BRASIL S.A.'),
    ('084', 'SISPRIME DO BRASIL - COOP'),
    ('085', 'COOPCENTRAL AILOS'),
    ('088', 'BANCO RANDON S.A.'),
    ('089', 'CREDISAN CC'),
    ('091', 'CCCM UNICRED CENTRAL RS'),
    ('092', 'BRK S.A. CFI'),
    ('093', 'POLOCRED SCMEPP LTDA.'),
    ('094', 'BANCO FINAXIS'),
    ('095', 'BANCO TRAVELEX S.A.'),
    ('096', 'BCO B3 S.A.'),
    ('097', 'CREDISIS - CENTRAL DE COOPERATIVAS DE CRÉDITO LTDA.'),
    ('098', 'CREDIALIANÇA CCR'),
    ('099', 'UNIPRIME COOPCENTRAL LTDA.'),
    ('100', 'PLANNER CV S.A.'),
    ('101', 'RENASCENCA DTVM LTDA'),
    ('102', 'XP INVESTIMENTOS CCTVM S/A'),
    ('104', 'CAIXA ECONOMICA FEDERAL'),
    ('105', 'LECCA CFI S.A.'),
    ('107', 'BCO BOCOM BBM S.A.'),
    ('108', 'PORTOCRED S.A. - CFI'),
    ('111', 'OLIVEIRA TRUST DTVM S.A.'),
    ('113', 'NEON CTVM S.A.'),
    ('114', 'CENTRAL COOPERATIVA DE CRÉDITO NO ESTADO DO ESPÍRITO SANTO'),
    ('117', 'ADVANCED CC LTDA'),
    ('119', 'BCO WESTERN UNION'),
    ('120', 'BCO RODOBENS S.A.'),
    ('121', 'BCO AGIBANK S.A.'),
    ('122', 'BCO BRADESCO BERJ S.A.'),
    ('124', 'BCO WOORI BANK DO BRASIL S.A.'),
    ('125', 'BANCO GENIAL'),
    ('126', 'BR PARTNERS BI'),
    ('127', 'CODEPE CVC S.A.'),
    ('128', 'BRAZA BANK S.A. BCO DE CÂMBIO'),
    ('129', 'UBS BB BI S.A.'),
    ('130', 'CARUANA SCFI'),
    ('131', 'TULLETT PREBON BRASIL CVC LTDA'),
    ('132', 'ICBC DO BRASIL BM S.A.'),
    ('133', 'CRESOL CONFEDERAÇÃO'),
    ('134', 'BGC LIQUIDEZ DTVM LTDA'),
    ('136', 'UNICRED DO BRASIL'),
    ('138', 'GET MONEY CC LTDA'),
    ('139', 'INTESA SANPAOLO BRASIL S.A. BM'),
    ('140', 'NU INVEST CORRETORA DE VALORES S.A.'),
    ('141', 'MASTER BI S.A.'),
    ('142', 'BROKER BRASIL CC LTDA.'),
    ('143', 'INTEX BANK BCO DE CÂMBIO S.A.'),
    ('144', 'EBURY BCO DE CÂMBIO S.A.'),
    ('145', 'LEVYCAM CCV LTDA'),
    ('146', 'GUITTA CC LTDA'),
    ('149', 'FACTA S.A. CFI'),
    ('157', 'ICAP DO BRASIL CTVM LTDA.'),
    ('159', 'CASA CREDITO S.A. SCM'),
    ('163', 'COMMERZBANK BRASIL S.A. - BCO MÚLTIPLO'),
    ('173', 'BRL TRUST DTVM SA'),
    ('174', 'PEFISA S.A. - C.F.I.'),
    ('177', 'GUIDE'),
    ('180', 'CM CAPITAL MARKETS CCTVM LTDA'),
    ('183', 'SOCRED SA - SCMEPP'),
    ('184', 'BCO ITAÚ BBA S.A.'),
    ('188', 'ATIVA S.A. INVESTIMENTOS CCTVM'),
    ('189', 'HS FINANCEIRA'),
    ('190', 'SERVICOOP'),
    ('191', 'NOVA FUTURA CTVM LTDA.'),
    ('194', 'UNIDA DTVM LTDA'),
    ('195', 'VALOR S/A SCFI'),
    ('196', 'FAIR CC S.A.'),
    ('197', 'STONE IP S.A.'),
    ('208', 'BANCO BTG PACTUAL S.A.'),
    ('212', 'BANCO ORIGINAL'),
    ('213', 'BCO ARBI S.A.'),
    ('217', 'BANCO JOHN DEERE S.A.'),
    ('218', 'BCO BS2 S.A.'),
    ('222', 'BCO CRÉDIT AGRICOLE BR S.A.'),
    ('224', 'BCO FIBRA S.A.'),
    ('233', 'BANCO CIFRA'),
    ('237', 'BCO BRADESCO S.A.'),
    ('241', 'BCO CLASSICO S.A.'),
    ('243', 'BANCO MASTER'),
    ('246', 'BCO ABC BRASIL S.A.'),
    ('249', 'BANCO INVESTCRED UNIBANCO S.A.'),
    ('250', 'BANCO BMG CONSIGNADO S.A.'),
    ('253', 'BEXS CC S.A.'),
    ('254', 'PARANA BCO S.A.'),
    ('259', 'MONEYCORP BCO DE CÂMBIO S.A.'),
    ('260', 'NU PAGAMENTOS - IP'),
    ('265', 'BCO FATOR S.A.'),
    ('266', 'BCO CEDULA S.A.'),
    ('268', 'BARI CIA HIPOTECÁRIA'),
    ('269', 'BCO HSBC S.A.'),
    ('270', 'SAGITUR CC - EM LIQUIDAÇÃO EXTRAJUDICIAL'),
    ('271', 'BPY CCTVM S.A.'),
    ('272', 'AGK CC S.A.'),
    ('273', 'COOP SULCREDI AMPLEA'),
    ('274', 'BMP SCMEPP LTDA'),
    ('276', 'BCO SENFF S.A.'),
    ('278', 'GENIAL INVESTIMENTOS CVM S.A.'),
    ('279', 'COOP DE PRIMAVERA DO LESTE'),
    ('280', 'WILL FINANCEIRA S.A.CFI'),
    ('281', 'CCR COOPAVEL'),
    ('283', 'RB INVESTIMENTOS DTVM LTDA.'),
    ('285', 'FRENTE CC S.A.'),
    ('286', 'UNIPRIME OURO - COOP DE OURO'),
    ('288', 'CAROL DTVM LTDA.'),
    ('289', 'EFX CC LTDA.'),
    ('290', 'PAGSEGURO INTERNET IP S.A.'),
    ('292', 'GALAPAGOS DTVM S.A.'),
    ('293', 'LASTRO RDV DTVM LTDA'),
    ('296', 'OZ CORRETORA DE CÂMBIO S.A.'),
    ('298', 'VIPS CC LTDA.'),
    ('299', 'BCO AFINZ S.A. - BM'),
    ('300', 'BCO LA NACION ARGENTINA'),
    ('301', 'DOCK IP S.A.'),
    ('305', 'FOURTRADE COR. DE CAMBIO LTDA'),
    ('306', 'PORTOPAR DTVM LTDA'),
    ('307', 'TERRA INVESTIMENTOS DTVM'),
    ('309', 'CAMBIONET CC LTDA'),
    ('310', 'VORTX DTVM LTDA.'),
    ('311', 'DOURADA CORRETORA'),
    ('312', 'HSCM SCMEPP LTDA.'),
    ('313', 'AMAZÔNIA CC LTDA.'),
    ('315', 'PI DTVM S.A.'),
    ('318', 'BCO BMG S.A.'),
    ('319', 'OM DTVM LTDA'),
    ('320', 'BOC BRASIL'),
    ('321', 'CREFAZ SCMEPP SA'),
    ('322', 'CCR DE ABELARDO LUZ'),
    ('323', 'MERCADO PAGO IP LTDA.'),
    ('324', 'CARTOS SCD S.A.'),
    ('325', 'ÓRAMA DTVM S.A.'),
    ('326', 'PARATI - CFI S.A.'),
    ('328', 'CECM FABRIC CALÇADOS SAPIRANGA'),
    ('329', 'QI SCD S.A.'),
    ('330', 'BANCO BARI S.A.'),
    ('331', 'OSLO CAPITAL DTVM SA'),
    ('332', 'ACESSO SOLUÇÕES DE PAGAMENTO S.A. - INSTITUIÇÃO DE PAGAMENTO'),
    ('334', 'BANCO BESA S.A.'),
    ('335', 'BANCO DIGIO'),
    ('336', 'BCO C6 S.A.'),
    ('340', 'SUPERDIGITAL I.P. S.A.'),
    ('341', 'ITAÚ UNIBANCO S.A.'),
    ('342', 'CREDITAS SCD'),
    ('343', 'FFA SCMEPP LTDA.'),
    ('348', 'BCO XP S.A.'),
    ('349', 'AL5 S.A. CFI'),
    ('350', 'COOP DE AGRICULTORES E AEROPORTUÁRIOS DO BRASIL'),
    ('352', 'TORO CTVM S.A.'),
    ('354', 'NECTON INVESTIMENTOS S.A CVM'),
    ('355', 'ÓTIMO SCD S.A.'),
    ('358', 'MIDWAY S.A. - SCFI'),
    ('359', 'ZEMA CFI S/A'),
    ('360', 'TRINUS CAPITAL DTVM'),
    ('362', 'CIELO IP S.A.'),
    ('363', 'SINGULARE CTVM S.A.'),
    ('364', 'EFÍ S.A. - IP'),
    ('365', 'SIMPAUL'),
    ('366', 'BCO SOCIETE GENERALE BRASIL'),
    ('367', 'VITREO DTVM S.A.'),
    ('368', 'BCO CSF S.A.'),
    ('370', 'BCO MIZUHO S.A.'),
    ('371', 'WARREN CVMC LTDA'),
    ('373', 'UP.P SEP S.A.'),
    ('374', 'REALIZE CFI S.A.'),
    ('376', 'BCO J.P. MORGAN S.A.'),
    ('377', 'BMS SCD S.A.'),
    ('378', 'BCO BRASILEIRO DE CRÉDITO S.A.'),
    ('379', 'CECM COOPERFORTE'),
    ('380', 'PICPAY'),
    ('381', 'BCO MERCEDES-BENZ S.A.'),
    ('382', 'FIDUCIA SCMEPP LTDA'),
    ('383', 'EBANX IP LTDA.'),
    ('384', 'GLOBAL SCM LTDA'),
    ('385', 'CECM DOS TRAB.PORT. DA G.VITOR'),
    ('386', 'NU FINANCEIRA S.A. CFI'),
    ('387', 'BCO TOYOTA DO BRASIL S.A.'),
    ('389', 'BCO MERCANTIL DO BRASIL S.A.'),
    ('390', 'BCO GM S.A.'),
    ('391', 'CCR DE IBIAM'),
    ('393', 'BCO VOLKSWAGEN S.A'),
    ('394', 'BCO BRADESCO FINANC. S.A.'),
    ('395', 'F D GOLD DTVM LTDA'),
    ('396', 'MAGALUPAY'),
    ('397', 'LISTO SCD S.A.'),
    ('398', 'IDEAL CTVM S.A.'),
    ('399', 'KIRTON BANK'),
    ('400', 'COOP CREDITAG'),
    ('401', 'IUGU IP S.A.'),
    ('402', 'COBUCCIO S.A. SCFI'),
    ('403', 'CORA SCFI'),
    ('404', 'SUMUP SCD S.A.'),
    ('406', 'ACCREDITO SCD S.A.'),
    ('407', 'SEFER INVESTIMENTOS DTVM LTDA'),
    ('408', 'BONUSPAGO SCD S.A.'),
    ('410', 'PLANNER SOCIEDADE DE CRÉDITO DIRETO'),
    ('411', 'VIA CERTA FINANCIADORA S.A. - CFI'),
    ('412', 'SOCIAL BANK S/A'),
    ('413', 'BCO BV S.A.'),
    ('414', 'LEND SCD S.A.'),
    ('415', 'BCO NACIONAL'),
    ('416', 'LAMARA SCD S.A.'),
    ('418', 'ZIPDIN SCD S.A.'),
    ('419', 'NUMBRS SCD S.A.'),
    ('421', 'CC LAR CREDI'),
    ('422', 'BCO SAFRA S.A.'),
    ('423', 'COLUNA S.A. DTVM'),
    ('425', 'SOCINAL S.A. CFI'),
    ('426', 'NEON FINANCEIRA - CFI S.A.'),
    ('427', 'CRED.UFES'),
    ('428', 'CREDSYSTEM SCD S.A.'),
    ('429', 'CREDIARE CFI S.A.'),
    ('430', 'CCR SEARA'),
    ('433', 'BR-CAPITAL DTVM S.A.'),
    ('435', 'DELCRED SCD S.A.'),
    ('438', 'TRUSTEE DTVM LTDA.'),
    ('439', 'ID CTVM'),
    ('440', 'CREDIBRF COOP'),
    ('442', 'MAGNETIS - DTVM'),
    ('443', 'CREDIHOME SCD'),
    ('444', 'TRINUS SCD S.A.'),
    ('445', 'PLANTAE CFI'),
    ('447', 'MIRAE ASSET (BRASIL) CCTVM LTDA.'),
    ('448', 'HEMERA DTVM LTDA.'),
    ('449', 'DM'),
    ('450', 'FITBANK IP'),
    ('451', 'J17 - SCD S/A'),
    ('452', 'CREDIFIT SCD S.A.'),
    ('454', 'MÉRITO DTVM LTDA.'),
    ('455', 'FÊNIX DTVM LTDA.'),
    ('456', 'BCO MUFG BRASIL S.A.'),
    ('457', 'UY3 SCD S/A'),
    ('458', 'HEDGE INVESTMENTS DTVM LTDA.'),
    ('459', 'CCM SERV. PÚBLICOS SP'),
    ('460', 'UNAVANTI SCD S/A'),
    ('461', 'ASAAS IP S.A.'),
    ('462', 'STARK SCD S.A.'),
    ('463', 'AZUMI DTVM'),
    ('464', 'BCO SUMITOMO MITSUI BRASIL S.A.'),
    ('465', 'CAPITAL CONSIG SCD S.A.'),
    ('467', 'MASTER S/A CCTVM'),
    ('468', 'PORTOSEG S.A. CFI'),
    ('469', 'PICPAY INVEST'),
    ('470', 'CDC SCD S.A.'),
    ('471', 'CECM SERV PUBL PINHÃO'),
    ('473', 'BCO CAIXA GERAL BRASIL S.A.'),
    ('475', 'BCO YAMAHA MOTOR S.A.'),
    ('477', 'CITIBANK N.A.'),
    ('478', 'GAZINCRED S.A. SCFI'),
    ('479', 'BCO ITAUBANK S.A.'),
    ('481', 'SUPERLÓGICA SCD S.A.'),
    ('482', 'SBCASH SCD'),
    ('484', 'MAF DTVM SA'),
    ('487', 'DEUTSCHE BANK S.A.BCO ALEMAO'),
    ('488', 'JPMORGAN CHASE BANK'),
    ('492', 'ING BANK N.V.'),
    ('495', 'BCO LA PROVINCIA B AIRES BCE'),
    ('505', 'BCO CREDIT SUISSE S.A.'),
    ('506', 'RJI'),
    ('507', 'SCFI EFÍ S.A.'),
    ('508', 'AVENUE SECURITIES DTVM LTDA.'),
    ('509', 'CELCOIN IP S.A.'),
    ('510', 'FFCRED SCD S.A.'),
    ('511', 'MAGNUM SCD'),
    ('512', 'FINVEST DTVM'),
    ('513', 'ATF SCD S.A.'),
    ('514', 'EXIM CC LTDA.'),
    ('516', 'QISTA S.A. CFI'),
    ('518', 'MERCADO CRÉDITO SCFI S.A.'),
    ('519', 'LIONS TRUST DTVM'),
    ('520', 'SOMAPAY SCD S.A.'),
    ('521', 'PEAK SEP S.A.'),
    ('522', 'RED SCD S.A.'),
    ('523', 'HR DIGITAL SCD'),
    ('524', 'WNT CAPITAL DTVM'),
    ('525', 'INTERCAM CC LTDA'),
    ('526', 'MONETARIE SCD'),
    ('527', 'ATICCA SCD S.A.'),
    ('528', 'REAG TRUST DTVM'),
    ('529', 'PINBANK IP'),
    ('530', 'SER FINANCE SCD S.A.'),
    ('531', 'BMP SCD S.A.'),
    ('532', 'EAGLE SCD S.A.'),
    ('533', 'SRM BANK'),
    ('534', 'EWALLY IP S.A.'),
    ('535', 'OPEA SCD'),
    ('536', 'NEON PAGAMENTOS S.A. IP'),
    ('537', 'MICROCASH SCMEPP LTDA.'),
    ('538', 'SUDACRED SCD S.A.'),
    ('539', 'SANTINVEST S.A. - CFI'),
    ('540', 'HBI SCD'),
    ('541', 'FDO GARANTIDOR CRÉDITOS'),
    ('542', 'CLOUDWALK IP LTDA'),
    ('543', 'COOPCRECE'),
    ('544', 'MULTICRED SCD S.A.'),
    ('545', 'SENSO CCVM S.A.'),
    ('546', 'U4C INSTITUIÇÃO DE PAGAMENTO S.A.'),
    ('547', 'BNK DIGITAL SCD S.A.'),
    ('548', 'RPW S.A. SCFI'),
    ('549', 'INTRA DTVM'),
    ('550', 'BEETELLER'),
    ('551', 'VERT DTVM LTDA.'),
    ('552', 'UZZIPAY IP S.A.'),
    ('553', 'PERCAPITAL SCD S.A.'),
    ('554', 'STONEX BANCO DE CÂMBIO S.A.'),
    ('555', 'PAN CFI'),
    ('556', 'SAYGO CÂMBIO'),
    ('557', 'PAGPRIME IP'),
    ('558', 'QI DTVM LTDA.'),
    ('559', 'KANASTRA CFI'),
    ('560', 'MAG IP LTDA.'),
    ('561', 'PAY4FUN IP S.A.'),
    ('562', 'AZIMUT BRASIL DTVM LTDA'),
    ('563', 'PROTEGE PAY CASH IP S.A.'),
    ('565', 'ÁGORA CTVM S.A.'),
    ('566', 'FLAGSHIP IP LTDA'),
    ('567', 'MERCANTIL FINANCEIRA'),
    ('568', 'BRCONDOS SCD S.A.'),
    ('569', 'CONTA PRONTA IP'),
    ('572', 'ALL IN CRED SCD S.A.'),
    ('575', 'DGBK CREDIT S.A. - SOCIEDADE DE CRÉDITO DIRETO.'),
    ('576', 'MERCADO BITCOIN IP LTDA'),
    ('577', 'AF DESENVOLVE SP S.A.'),
    ('578', 'SICRES'),
    ('579', 'QUADRA SCD'),
    ('580', 'CCCPOUPINV SUL E SUDESTE - CENTRAL SUL/SUDESTE'),
    ('581', 'CENTRAL NORDESTE'),
    ('582', 'CCC POUP INV DE MS GO DF E TO'),
    ('583', 'CCC POUP INV DO CENTRO NORTE DO BRASIL'),
    ('584', 'CCC POUP E INV DOS ESTADOS DO PR SP E RJ'),
    ('585', 'SETHI SCD SA'),
    ('586', 'Z1 IP LTDA.'),
    ('587', 'FIDD DTVM LTDA.'),
    ('588', 'PROVER PROMOCAO DE VENDAS IP LTDA.'),
    ('589', 'G5 SCD SA'),
    ('590', 'REPASSES FINANCEIROS E SOLUCOES TECNOLOGICAS IP S.A.'),
    ('591', 'BANVOX DTVM'),
    ('592', 'MAPS IP LTDA.'),
    ('593', 'TRANSFEERA IP S.A.'),
    ('594', 'ASA SOCIEDADE DE CRÉDITO DIRETO S.A.'),
    ('595', 'ZOOP MEIOS DE PAGAMENTO'),
    ('597', 'ISSUER IP LTDA.'),
    ('599', 'AGORACRED S/A SCFI'),
    ('600', 'BCO LUSO BRASILEIRO S.A.'),
    ('604', 'BCO INDUSTRIAL DO BRASIL S.A.'),
    ('610', 'BCO VR S.A.'),
    ('611', 'BCO PAULISTA S.A.'),
    ('612', 'BCO GUANABARA S.A.'),
    ('613', 'OMNI BANCO S.A.'),
    ('614', 'NITRO SCD S.A.'),
    ('615', 'SMART SOLUTIONS GROUP IP LTDA'),
    ('619', 'TRIO IP LTDA.'),
    ('620', 'REVOLUT SCD S.A.'),
    ('623', 'BANCO PAN'),
    ('626', 'BCO C6 CONSIG'),
    ('630', 'BCO LETSBANK S.A.'),
    ('632', 'Z-ON SCD S.A.'),
    ('633', 'BCO RENDIMENTO S.A.'),
    ('634', 'BCO TRIANGULO S.A.'),
    ('636', 'GIRO - SCD S/A'),
    ('637', 'BCO SOFISA S.A.'),
    ('643', 'BCO PINE S.A.'),
    ('644', '321 SCD S.A.'),
    ('646', 'DM SA CFI'),
    ('651', 'PAGARE IP S.A.'),
    ('652', 'ITAÚ UNIBANCO HOLDING S.A.'),
    ('653', 'BANCO VOITER'),
    ('654', 'BCO DIGIMAIS S.A.'),
    ('655', 'BCO VOTORANTIM S.A.'),
    ('659', 'ONEKEY PAYMENTS IP S.A.'),
    ('660', 'PAGME IP LTDA'),
    ('661', 'FREEX CC S.A.'),
    ('662', 'WE PAY OUT IP LTDA.'),
    ('663', 'ACTUAL DTVM S.A.'),
    ('664', 'EAGLE IP LTDA.'),
    ('665', 'STARK BANK S.A. - IP'),
    ('666', 'URBANO S.A. SCFI'),
    ('671', 'ZERO'),
    ('674', 'HINOVA PAY IP S.A.'),
    ('676', 'DUFRIO CFI S.A.'),
    ('707', 'BCO DAYCOVAL S.A'),
    ('712', 'OURIBANK S.A.'),
    ('719', 'BANCO MASTER MÚLTIPLO'),
    ('720', 'BCO RNX S.A.'),
    ('739', 'BCO CETELEM S.A.'),
    ('741', 'BCO RIBEIRAO PRETO S.A.'),
    ('743', 'BANCO SEMEAR'),
    ('745', 'BCO CITIBANK S.A.'),
    ('746', 'BCO MODAL S.A.'),
    ('747', 'BCO RABOBANK INTL BRASIL S.A.'),
    ('748', 'BCO COOPERATIVO SICREDI S.A.'),
    ('751', 'SCOTIABANK BRASIL'),
    ('752', 'BCO BNP PARIBAS BRASIL S A'),
    ('753', 'NOVO BCO CONTINENTAL S.A. - BM'),
    ('754', 'BANCO SISTEMA'),
    ('755', 'BOFA MERRILL LYNCH BM S.A.'),
    ('756', 'BANCO SICOOB S.A.'),
    ('757', 'BCO KEB HANA DO BRASIL S.A.'),
)