"""empty message

Revision ID: 049df145d898
Revises: e93ffe0c89e3
Create Date: 2026-04-25 13:44:31.178144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049df145d898'
down_revision = 'e93ffe0c89e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
