"""empty message

Revision ID: 184610a405a1
Revises: 538db7571881
Create Date: 2026-04-19 20:13:37.471952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184610a405a1'
down_revision = '538db7571881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('updated_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('updated_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)

    # ### end Alembic commands ###
