"""empty message

Revision ID: 1a351217b7d1
Revises: f5e3f12588ee
Create Date: 2026-02-13 01:10:29.979453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a351217b7d1'
down_revision = 'f5e3f12588ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
