"""empty message

Revision ID: 203a9b5a35f5
Revises: dfde4d07136b
Create Date: 2026-02-16 19:23:56.749955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203a9b5a35f5'
down_revision = 'dfde4d07136b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agreements_debt_id'), ['debt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agreements_debt_id'))

    # ### end Alembic commands ###
