"""empty message

Revision ID: 244e03fe4282
Revises: ad5753dfe6b9
Create Date: 2026-02-13 22:25:57.284841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244e03fe4282'
down_revision = 'ad5753dfe6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('discount_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('discount_applied',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
