"""empty message

Revision ID: 3d9c49fca4ad
Revises: 973a6559d118
Create Date: 2026-04-12 16:43:15.454537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9c49fca4ad'
down_revision = '973a6559d118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document', sa.String(length=14), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('document')

    # ### end Alembic commands ###
