"""empty message

Revision ID: 538db7571881
Revises: b1435fa7703c
Create Date: 2026-04-19 18:10:12.027658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538db7571881'
down_revision = 'b1435fa7703c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.alter_column('old_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OPEN', 'IN_AGREEMENT', 'PAID', 'DEFAULTED', 'CANCELLED', name='debt_status_enum'),
               existing_nullable=True, postgresql_using='old_status::debt_status_enum')
        batch_op.alter_column('new_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('OPEN', 'IN_AGREEMENT', 'PAID', 'DEFAULTED', 'CANCELLED', name='debt_status_enum'),
               existing_nullable=True, postgresql_using='new_status::debt_status_enum')
        batch_op.alter_column('old_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('new_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.create_index('ix_debt_history_debt_id_changed_at', ['debt_id', 'changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_index('ix_debt_history_debt_id_changed_at')
        batch_op.alter_column('new_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('old_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('new_status',
               existing_type=sa.Enum('OPEN', 'IN_AGREEMENT', 'PAID', 'DEFAULTED', 'CANCELLED', name='debt_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('old_status',
               existing_type=sa.Enum('OPEN', 'IN_AGREEMENT', 'PAID', 'DEFAULTED', 'CANCELLED', name='debt_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
