"""empty message

Revision ID: 587c11f8cae3
Revises: 80ec74280801
Create Date: 2026-04-24 23:36:29.699220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587c11f8cae3'
down_revision = '80ec74280801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    op.execute(
        "UPDATE users SET must_change_password = FALSE"
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'must_change_password',
            existing_type=sa.BOOLEAN(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
