"""empty message

Revision ID: 80ec74280801
Revises: ee979f6f4b54
Create Date: 2026-04-20 20:56:31.276999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ec74280801'
down_revision = 'ee979f6f4b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debt_history_debt_id'), ['debt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debt_history_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_history_event_type'))
        batch_op.drop_index(batch_op.f('ix_debt_history_debt_id'))

    # ### end Alembic commands ###
