"""empty message

Revision ID: 9bb05ac56afa
Revises: a7e7fbad7615
Create Date: 2026-02-12 22:28:57.781742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb05ac56afa'
down_revision = 'a7e7fbad7615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_traded', sa.Float(), nullable=False),
    sa.Column('qtd_instalments', sa.Integer(), nullable=False),
    sa.Column('discount_applied', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agreements')
    # ### end Alembic commands ###
