"""empty message

Revision ID: 9c0aa5148f45
Revises: 52fa4c5f90f4
Create Date: 2026-04-19 23:10:13.759722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9c0aa5148f45'
down_revision = '52fa4c5f90f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM(
	'STATUS_CHANGE',
	'INTEREST_APPLIED',
	'DISCOUNT_APPLIED',
	'VALUE_CORRECTION',
	'AGREEMENT_CREATED',
	'AGREEMENT_CANCELLED',
	'AGREEMENT_COMPLETED',
	'DEBT_CREATED',
	'DEBT_CANCELLED',
	'DEBT_DEFAULTED',
	name='debt_history_type_enum'
    )

    enum.create(op.get_bind())

    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', enum, nullable=False))
        batch_op.create_index(batch_op.f('ix_debt_history_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_history_event_type'))
        batch_op.drop_column('event_type')

    enum = postgresql.ENUM(name='debt_history_type_enum')
    enum.drop(op.get_bind())

    # ### end Alembic commands ###
