"""empty message

Revision ID: ad5753dfe6b9
Revises: 1a351217b7d1
Create Date: 2026-02-13 03:58:12.934026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5753dfe6b9'
down_revision = '1a351217b7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_value', sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('entry_value', sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('first_due_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('debt_id', sa.Integer(), nullable=False))
        batch_op.alter_column('total_traded',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'debts', ['debt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total_traded',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('debt_id')
        batch_op.drop_column('first_due_date')
        batch_op.drop_column('entry_value')
        batch_op.drop_column('installment_value')

    # ### end Alembic commands ###
