"""empty message

Revision ID: b1435fa7703c
Revises: 6ae4fce53065
Create Date: 2026-04-19 17:59:24.886060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1435fa7703c'
down_revision = '6ae4fce53065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('old_value', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('new_value', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debt_history_debt_id'), ['debt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debt_history_debt_id'))

    op.drop_table('debt_history')
    # ### end Alembic commands ###
