"""empty message

Revision ID: bf242b2b9fd6
Revises: dc9abbe96550
Create Date: 2026-02-14 22:29:54.110618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf242b2b9fd6'
down_revision = 'dc9abbe96550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installments_quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('instalments_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instalments_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('installments_quantity')

    # ### end Alembic commands ###
