"""empty message

Revision ID: c1cc5c92d357
Revises: 9c0aa5148f45
Create Date: 2026-04-20 12:15:24.043822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cc5c92d357'
down_revision = '9c0aa5148f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_column('extra')

    # ### end Alembic commands ###
