"""empty message

Revision ID: dc9abbe96550
Revises: 244e03fe4282
Create Date: 2026-02-13 23:30:51.907164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9abbe96550'
down_revision = '244e03fe4282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instalments_quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('qtd_instalments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_instalments', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('instalments_quantity')

    # ### end Alembic commands ###
