"""empty message

Revision ID: dfde4d07136b
Revises: bf242b2b9fd6
Create Date: 2026-02-15 20:55:13.751584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'dfde4d07136b'
down_revision = 'bf242b2b9fd6'
branch_labels = None
depends_on = None

agreement_status = postgresql.ENUM(
    'DRAFT',
    'ACTIVE',
    'CANCELLED',
    'COMPLETED',
    name='agreementstatus'
)


def upgrade():
    agreement_status.create(op.get_bind(), checkfirst=True)	
   
   
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CANCELLED', 'COMPLETED', name='agreementstatus'), nullable=True))

    # ### end Alembic commands ###
    op.execute("UPDATE agreements SET status = 'DRAFT'")

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
    agreement_status.drop(op.get_bind(), checkfirst=True)
