"""empty message

Revision ID: f0b3a0da17ad
Revises: 049df145d898
Create Date: 2026-05-05 00:49:19.548818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0b3a0da17ad'
down_revision = '049df145d898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agreements_debt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debts', ['debt_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('debt_history_debt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debts', ['debt_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('debts_debtor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('debts_creditor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'debtors', ['debtor_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'creditors', ['creditor_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('installments_agreement_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'agreements', ['agreement_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_installment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'installments', ['installment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_installment_id_fkey'), 'installments', ['installment_id'], ['id'])

    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('installments_agreement_id_fkey'), 'agreements', ['agreement_id'], ['id'])

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('debts_creditor_id_fkey'), 'creditors', ['creditor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('debts_debtor_id_fkey'), 'debtors', ['debtor_id'], ['id'])

    with op.batch_alter_table('debt_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('debt_history_debt_id_fkey'), 'debts', ['debt_id'], ['id'])

    with op.batch_alter_table('agreements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('agreements_debt_id_fkey'), 'debts', ['debt_id'], ['id'])

    # ### end Alembic commands ###
