"""empty message

Revision ID: f5e3f12588ee
Revises: 2a6fc4f602ea
Create Date: 2026-02-13 00:58:13.632886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e3f12588ee'
down_revision = '2a6fc4f602ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('agreement_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'agreements', ['agreement_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agreement_id')
        batch_op.drop_column('value')

    # ### end Alembic commands ###
